services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: tt
      POSTGRES_PASSWORD: tt
      POSTGRES_DB: tt
    ports:
      - "5544:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tt -d tt"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
